[package]
name = "auth"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
storage = { path = "../storage" }
jsonwebtoken = "9"
argon2 = "0.5"
sha2 = "0.11"
hmac = "0.12"
totp-rs = { version = "5", default-features = false, features = ["gen_secret"] }
rand = "0.8"
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
